services:
  forum-service:
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/forum-service

  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"

